services:
  mysql-1:
    image: mysql:latest
    container_name: mysql-1
    environment:
      MYSQL_DATABASE: department_db
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - 3307:3306
   